### ISSUE TITLE
Ajouter bouton de retour à l'emprise initiale

### ISSUE THREAD

**Issue by RaphaelChochon** [PnMercantour/PortailCarto#2]
Lat et Long récupérées depuis `maps.json`
Un plugin Leaflet existe : Leaflet.EasyButton
- https://github.com/CliffCloud/Leaflet.EasyButton
- Démo : http://danielmontague.com/projects/easyButton.js/v1/examples/

C'est ce que semble utiliser @Chrispnv pour l'appli "Cables"

**Comment by RaphaelChochon** [comment]
Done 3a7c5ea375dae1c1d7aa3a7b71476a8d171c3225

**Comment by camillemonchicourt** [comment]
Dans Geotrek-rando ils utilisent un control appelé reset-view - https://github.com/makinacorpus/Geotrek-rando/search?utf8=%E2%9C%93&q=resetview

Dans Geotrek-admin, il l'appellent zoom-out - https://github.com/makinacorpus/Geotrek/search?utf8=%E2%9C%93&q=leaflet-control-zoom-out

Je n'ai pas trouvé si il existait ce module de manière indépendante et installable. 

Je l'ai aussi retrouvé dans le projet Django-leaflet - https://github.com/makinacorpus/django-leaflet/search?utf8=%E2%9C%93&q=resetview

@TheoLechemia, concernant EasyButton, je ne connaissais pas, mais ça peut être une piste pour ajouter des controls personnalisés (comme le type d'affichage des observations) directement dans la carte.

**Comment by RaphaelChochon** [comment]
@camillemonchicourt Effectivement, j'ai trouvé ça qui a l'air de faire le taff : https://github.com/torfsen/leaflet.zoomhome

Mais EasyButton fait le taff aussi de mon côté, et on peut lui imaginer d'autres fonctions;)

**Comment by Chrispnv** [comment]
Sur notre appli Câbles le EasyButton pour le reset view fonctionne bien.
Voir dans https://github.com/PnVanoise/cables/blob/master/web/js/services/mapServices.js, le bloc CONTROL EMPRISE INITIALE (ligne 158).
empriseInit, zoomInit sont récupérés depuis https://github.com/PnVanoise/cables/blob/master/web/js/resources/defaultMap.json avec configServ.getUrl('js/resources/defaultMap.json' .... (méthode perso à câbles, mais une méthode pour lire du json à travers http va bien).
